universibo_sso_login:
    pattern:  /secured
    defaults: { _controller: 'universibo_sso.controller.security:loginAction' }

universibo_sso_logout:
    pattern:  /secured/logout
    defaults: { _controller: 'universibo_sso.controller.security:logoutAction' }

universibo_sso_metadata:
    pattern:  /metadata
    defaults: { _controller: 'universibo_sso.controller.metadata:indexAction' }
