universibo_sso_homepage:
    pattern:  /
    defaults: { _controller: 'universibo_sso.controller.userbox:indexAction' }

universibo_sso_login:
    pattern:  /login
    defaults: { _controller: 'universibo_sso.controller.security:loginAction' }
    
universibo_sso_logout:
    pattern:  /logout
    defaults: { _controller: 'universibo_sso.controller.security:logoutAction' }    

universibo_sso_metadata:
    pattern:  /metadata
    defaults: { _controller: 'universibo_sso.controller.metadata:indexAction' }
