services:
    universibo_sso.controller.userbox:
        class: Universibo\Bundle\SSOBundle\Controller\UserBoxController
        arguments: ['%universibo_sso.idp_url.info%','%universibo_sso.idp_url.logout%', '@templating', '@router', '%universibo_sso.route.after_logout%']
    universibo_sso.controller.security:
        class: Universibo\Bundle\SSOBundle\Controller\SecurityController
        arguments: ['@templating']
