services:
    universibo_sso.controller.userbox:
        class: Universibo\Bundle\SSOBundle\Controller\UserBoxController
        arguments:
          - '%universibo_shibboleth.idp_url.info%'
          - '%universibo_shibboleth.idp_url.logout%'
          - '@templating'
          - '@router'
          - '@security.context'
