parameters:
#    universibo_core.example.class: Universibo\Bundle\CoreBundle\Example

services:
#    universibo_core.example:
#        class: %universibo_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
