services:
   universibo_core.repository.user:
     class: Universibo\Bundle\CoreBundle\Entity\UserRepository
     factory_service: doctrine.orm.entity_manager
     factory_method: getRepository
     arguments: ['Universibo\Bundle\CoreBundle\Entity\User']
