parameters:
    universibo_core.channel.router.class: 'Universibo\Bundle\CoreBundle\Routing\ChannelRouter'

services:
    universibo_core.routing.channel:
        class: '%universibo_core.channel.router.class%'
        arguments: ['@router']
