UniversiboDidacticsBundle:
    resource: "@UniversiboDidacticsBundle/Controller/"
    type:     annotation
    prefix:   /

UniversiboContentBundle:
    resource: "@UniversiboContentBundle/Controller/"
    type:     annotation
    prefix:   /

UniversiboCoreBundle:
    resource: "@UniversiboCoreBundle/Resources/config/routing.yml"
    prefix:   /

UniversiboSearchBundle:
    resource: "@UniversiboSearchBundle/Resources/config/routing.yml"
    prefix:   /search

UniversiboSSOBundle:
    resource: "@UniversiboSSOBundle/Resources/config/routing.yml"
    prefix:   /sso

UniversiboWebsiteBundle:
    resource: "@UniversiboWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
