UniversiboContentBundle:
    resource: "@UniversiboContentBundle/Controller/"
    type:     annotation
    prefix:   /

UniversiboCoreBundle:
    resource: "@UniversiboCoreBundle/Resources/config/routing.yml"
    prefix:   /

UniversiboSearchBundle:
    resource: "@UniversiboSearchBundle/Resources/config/routing.yml"
    prefix:   /search

UniversiboSSOBundle:
    resource: "@UniversiboSSOBundle/Resources/config/routing.yml"
    prefix:   /sso

UniversiboWebsiteBundle:
    resource: "@UniversiboWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
