UniversiboCoreBundle:
    resource: "@UniversiboCoreBundle/Resources/config/routing.yml"
    prefix:   /

UniversiboSearchBundle:
    resource: "@UniversiboSearchBundle/Resources/config/routing.yml"
    prefix:   /search

UniversiboWebsiteBundle:
    resource: "@UniversiboWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /v3
    
UniversiboLegacyBundle:
    resource: "@UniversiboLegacyBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
