UniversiboSSOBundle:
    resource: "@UniversiboSSOBundle/Resources/config/routing.yml"
    prefix:   /sso

UniversiBODidacticsBundle:
    resource: "@UniversiBODidacticsBundle/Controller/"
    type:     annotation
    prefix:   /admin/didactics

UniversiBOWebsiteBundle:
    resource: "@UniversiBOWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

UniversiBOAnswersBundle:
    resource: "@UniversiBOAnswersBundle/Controller/"
    type:     annotation
    prefix:   /answers


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
