UniversiboCoreBundle:
    resource: "@UniversiboCoreBundle/Resources/config/routing.yml"
    prefix:   /

UniversiboWebsiteBundle:
    resource: "@UniversiboWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /v3
    
UniversiboLegacyBundle:
    resource: "@UniversiboLegacyBundle/Resources/config/routing.yml"
    prefix:   /

UniversiboShibbolethBundle:
    resource: "@UniversiboShibbolethBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
