UniversiBOLifeChatBundle:
    resource: "@UniversiBOLifeChatBundle/Controller/"
    type:     annotation
    prefix:   /lifechat

UniversiBODidacticsBundle:
    resource: "@UniversiBODidacticsBundle/Controller/"
    type:     annotation
    prefix:   /admin/didactics

UniversiBOWebsiteBundle:
    resource: "@UniversiBOWebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
