security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    factories:
        - "%kernel.root_dir%/../src/Universibo/Bundle/WebsiteBundle/Resources/config/security_factories.xml"

    providers:
        legacy:
            id: universibo_legacy.repository.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            legacy: true
            anonymous: ~
            form_login:
                login_path: /login
            logout:
                path:   /logout
                target: /logoutAfter

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/my, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
