security:
    encoders:
        Universibo\Bundle\CoreBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:
          - ROLE_USER
          - ROLE_COLLABORATOR
          - ROLE_PROFESSOR
          - ROLE_STAFF
        ROLE_PROFESSOR: [ROLE_TUTOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
            logout:
                path:   /logout
                target: /
                handler:
                  - universibo_shibboleth.logout_handler
                  - universibo_forum.logout_handler
            shibboleth: ~
    access_control:
      - { path: ^/my, roles: IS_AUTHENTICATED_FULLY }
      - { path: \badd\b, roles: IS_AUTHENTICATED_FULLY }
      
      - { path: \bdelete\b, roles: IS_AUTHENTICATED_FULLY }
      - { path: \bedit\b, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/admin, roles: ROLE_ADMIN }
      - { path: ^/gestione, roles: ROLE_COLLABORATOR }
      - { path: ^/role, roles: IS_AUTHENTICATED_FULLY }
      - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
