privacy:
  pattern: /privacy/
  defaults: { _controller: 'UniversiboWebsiteBundle:Privacy:index' }

privacy_accept:
  pattern: /privacy/accept/
  defaults: { _controller: 'UniversiboWebsiteBundle:Privacy:accept' }
  requirements: { _method: POST }

rss:
  pattern: /rss/{idCanale}/
  defaults: { _controller: 'UniversiboWebsiteBundle:Rss:index' }
  requirements: { idCanale: \d+ }
