rss:
  path: /rss/{idCanale}/
  defaults: { _controller: 'UniversiboWebsiteBundle:Rss:index' }
  requirements: { idCanale: \d+ }
universibo_website_auth_failed:
  path: /auth-failed/
  defaults: { _controller: 'UniversiboWebsiteBundle:AuthFailed:index' }
universibo_website_rules:
  path: /regolamento/
  defaults: { _controller: 'UniversiboWebsiteBundle:Rules:index' }
universibo_website_rules_accept:
  path: /regolamento/accetta/
  defaults: { _controller: 'UniversiboWebsiteBundle:Rules:accept' }
  methods: [POST]
universibo_website_profile_edit:
  path: /my/profile/
  defaults: { _controller: 'UniversiboWebsiteBundle:Profile:edit' }
universibo_website_profile_update:
  path: /my/profile/update/
  defaults: { _controller: 'UniversiboWebsiteBundle:Profile:update' }
  methods: [POST]
universibo_website_sitemap:
  path: /sitemap.xml
  defaults: { _controller: 'UniversiboWebsiteBundle:Sitemap:index' }
universibo_website_contact_verify:
  path: /my/email/verify/{token}/
  defaults: { _controller: 'UniversiboWebsiteBundle:Contact:verify' }
  methods: [GET]
universibo_website_contact_cancel:
  path: /my/email/cancel/{token}/
  defaults: { _controller: 'UniversiboWebsiteBundle:Contact:cancel' }
  methods: [GET]
