rss:
  pattern: /rss/{idCanale}/
  defaults: { _controller: 'UniversiboWebsiteBundle:Rss:index' }
  requirements: { idCanale: \d+ }
universibo_website_auth_failed:
  pattern: /auth-failed/
  defaults: { _controller: 'UniversiboWebsiteBundle:AuthFailed:index' }
universibo_website_rules:
  pattern: /regolamento/
  defaults: { _controller: 'UniversiboWebsiteBundle:Rules:index' }
universibo_website_rules_accept:
  pattern: /regolamento/accetta/
  defaults: { _controller: 'UniversiboWebsiteBundle:Rules:accept' }
  requirements: { _method: POST }
universibo_website_profile_edit:
  pattern: /my/profile/
  defaults: { _controller: 'UniversiboWebsiteBundle:Profile:edit' }
universibo_website_profile_update:
  pattern: /my/profile/update/
  defaults: { _controller: 'UniversiboWebsiteBundle:Profile:update' }
  requirements: { _method: POST }
universibo_website_contact_verify:
  pattern: /my/email/verify/
  defaults: { _controller: 'UniversiboWebsiteBundle:Contact:verify' }
  requirements: { _method: GET }
universibo_website_contact_cancel:
  pattern: /my/email/cancel/
  defaults: { _controller: 'UniversiboWebsiteBundle:Contact:cancel' }
  requirements: { _method: GET }
