services:
  universibo_didactics.repository.subject:
    class: Universibo\Bundle\DidacticsBundle\Entity\SubjectRepository
    factory_service: doctrine.orm.entity_manager
    factory_method: getRepository
    arguments: ['Universibo\Bundle\DidacticsBundle\Entity\Subject']
